CLASS_NAMES: ['DCM', 'NOR', 'MINF', 'HCM', 'RV']

ROOT_DIR: /home/s2020153/cardiac/cardiac_pillars

EXP_GROUP_PATH: cardiac

TAG: pointpillars

DATA_CONFIG:
    POINT_FEATURE_ENCODING: {
        encoding_type: absolute_coordinates_encoding,
        used_feature_list: [ 'x', 'y', 'z', 'frame', 'category' ],
        src_feature_list: [ 'x', 'y', 'z', 'frame', 'category' ],
          }

    DATA_PROCESSOR:
        - NAME: shuffle_points
          SHUFFLE_ENABLED: {
            'train': True,
            'test': False
          }

        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.16, 0.16, 4]
          MAX_POINTS_PER_VOXEL: 32
          MAX_NUMBER_OF_VOXELS: {
            'train': 16000,
            'test': 40000
          }

    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['placeholder']
        AUG_CONFIG_LIST:
            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.95, 1.05]

MODEL:
    NAME: PointPillar

    VFE:
        NAME: PillarVFE
        WITH_DISTANCE: False
        USE_ABSLOTE_XYZ: True
        USE_NORM: True
        NUM_FILTERS: [64]

    MAP_TO_BEV:
        NAME: PointPillarScatter
        NUM_BEV_FEATURES: 64

    BACKBONE_2D:
#        NAME: BaseBEVBackbone
#        LAYER_NUMS: [3, 5, 5]
#        LAYER_STRIDES: [2, 2, 2]
#        NUM_FILTERS: [64, 128, 256]
#        UPSAMPLE_STRIDES: [1, 2, 4]
#        NUM_UPSAMPLE_FILTERS: [128, 128, 128]

    CLASSIFIER:
        NAME: DenseNet

OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 4
    NUM_EPOCHS: 80

    OPTIMIZER: adam_onecycle
    LR: 0.003
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
